"""
Communication-network package: a random regular gossip graph with random link
latencies exposed as a broadcast-latency oracle, plus the quenched AC-path
latency profiles and their ping-data calibration.
"""

from .graph import (
    DEFAULT_C,
    eccentricity_survival,
    edge_endpoints,
    graph_distance_survival,
    mean_eccentricity_theory,
    mean_graph_distance_theory,
    sample_regular_graph,
)
from .latency import (
    DEFAULT_D,
    DEFAULT_LAM,
    DEFAULT_RHO,
    broadcast_completion_quantile,
    broadcast_delays,
    broadcast_latency,
    broadcast_latency_theory,
    lam_from_rho,
    mean_delay_theory,
    mean_pairwise_delay,
    propagation_exponent,
    rho_from_lam,
    sample_broadcast_latencies,
    sample_edge_latencies,
    sample_pairwise_delays,
    weighted_broadcast_latency,
)
from .ping_data import (
    CONTINENTS,
    DEFAULT_RTT_TO_ONEWAY,
    PINGS_CSV,
    REGION_WEIGHTS,
    city_continent,
    directional_asymmetry,
    load_pings,
    normalise_weights,
    ping_link_moments,
    ping_link_population,
    symmetrised_city_pairs,
)
from .lognormal_latency import (
    LogNormalParams,
    link_moments,
    lognormal_from_moments,
    lognormal_moments,
    per_set_sd_moments,
    sample_lognormal_links,
)
from .jitter import (
    JitterParams,
    ac_path_links,
    jitter_moments,
)
from .latency_profile import (
    LatencyProfile,
    LatencyProfileParams,
    is_homogeneous,
    profile_broadcast_latency,
    sample_latency_profile,
)

__all__ = [
    "DEFAULT_C",
    "DEFAULT_D",
    "DEFAULT_LAM",
    "DEFAULT_RHO",
    "sample_regular_graph",
    "edge_endpoints",
    "mean_graph_distance_theory",
    "graph_distance_survival",
    "eccentricity_survival",
    "mean_eccentricity_theory",
    "lam_from_rho",
    "rho_from_lam",
    "sample_edge_latencies",
    "broadcast_delays",
    "sample_pairwise_delays",
    "mean_pairwise_delay",
    "broadcast_completion_quantile",
    "broadcast_latency",
    "sample_broadcast_latencies",
    "propagation_exponent",
    "mean_delay_theory",
    "broadcast_latency_theory",
    "LatencyProfile",
    "LatencyProfileParams",
    "sample_latency_profile",
    "CONTINENTS",
    "REGION_WEIGHTS",
    "DEFAULT_RTT_TO_ONEWAY",
    "PINGS_CSV",
    "load_pings",
    "city_continent",
    "symmetrised_city_pairs",
    "normalise_weights",
    "directional_asymmetry",
    "ping_link_moments",
    "ping_link_population",
    "LogNormalParams",
    "lognormal_from_moments",
    "lognormal_moments",
    "link_moments",
    "per_set_sd_moments",
    "sample_lognormal_links",
    "weighted_broadcast_latency",
    "profile_broadcast_latency",
    "is_homogeneous",
    "JitterParams",
    "jitter_moments",
    "ac_path_links",
]
